name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: historical-docs-chat-frontend

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/historical-docs-chat-frontend/backend-repo/backend-image:latest .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/historical-docs-chat-frontend/backend-repo/backend-image:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy historical-docs-backend \
            --image us-central1-docker.pkg.dev/historical-docs-chat-frontend/backend-repo/backend-image:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
